name 'awesome_customer'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awesome_customer'
long_description 'Installs/Configures awesome_customer'
version '0.1.0'
